### ISSUE TITLE
Sound card

### ISSUE THREAD

**Issue by dwright213** [szymonkaliski/LoopPI2#2]
Hello, I just had a question before I dive into trying to make this work: 
It seems that the sound card referenced in the thread you link to is no longer manufactured or sold by Element14. Is there a thing I should be looking for in a possible equivalent?

**Comment by szymonkaliski** [comment]
Oh what a shame. I'd look for any RPI-compatible soundcard with good DAC and ADC, there should be something out there! Parts of setup related to audio will be different then, but the looper code and MIDI controls should work exactly the same. Good luck :)
